name: Build EXE

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --add-data "song.wav:." minecraft_adventure.py

    - name: Archive build output (EXE or ZIP)
      run: |
        if ls dist/*.exe 1> /dev/null 2>&1; then
          echo "Found EXE, uploading..."
          echo "exe" > artifact_type.txt
        elif ls dist/*.zip 1> /dev/null 2>&1; then
          echo "Found ZIP, extracting..."
          unzip -o dist/*.zip -d dist/
          echo "zip" > artifact_type.txt
        else
          echo "❌ No supported artifact (.exe or .zip) found in dist/"
          exit 1
        fi

    - name: Upload extracted EXE artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: exe-artifact
        path: |
          dist/*.exe
          artifact_type.txt
