name: Build EXE

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        if (Test-Path requirements.txt) {
          pip install -r requirements.txt
        }
      shell: pwsh

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --add-data "song.wav;." minecraft_adventure.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: exe-artifact
        path: dist/*.exe
